<a href="https://colab.research.google.com/github/uremember809/Project-Euler/blob/master/Project_Euler(1_5).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import time
import numpy as np

#Multiples of 3 and 5
## Problem 1 
If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9. The sum of these multiples is 23.

Find the sum of all the multiples of 3 or 5 below 1000.

## Find the numbers, put the in a list, and sum it

In [0]:
def three_five(x):
  s = set()
  for i in range(1, x):
    if (i % 3 == 0 or i % 5 == 0):
      s.add(i)
  return s

In [4]:
%timeit sum(three_five(1000))

10000 loops, best of 3: 183 µs per loop

## Direct sum them together function

In [0]:
def three_five_sum(x):
  s = 0
  for i in range(1, x):
    if (i % 3 == 0 or i % 5 == 0):
      s += i
  return s

In [6]:
%timeit three_five_sum(1000)

10000 loops, best of 3: 146 µs per loop

Direct method is faster

#Even Fibonacci numbers
## Problem 2 
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

## Build a list of fibonacci numbers that are less than x, the build a list of even number in it and sum it

In [0]:
def fib_under(x):
  i = j = 1
  f = []
  
  while j < x:    
    f.append(j)
    i, j = j, i +j
  
  return f

In [8]:
fib_under(200)

[1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144]

In [9]:
% timeit sum([i for i in fib_under(4000000) if i % 2 == 0])

100000 loops, best of 3: 9.49 µs per loop

## Build a list of fibonacci numbers that are less than x and even, then sum it

In [0]:
def even_fib_under(x):
  
  i = j = 1
  f = []
  while j < x:
    if j % 2 == 0:
      f.append(j)
    i, j = j, i +j      
    
  return f

In [11]:
even_fib_under(100000)

[2, 8, 34, 144, 610, 2584, 10946, 46368]

In [12]:
%timeit sum(even_fib_under(4000000))

100000 loops, best of 3: 6.3 µs per loop

## A function that return a list is always dangeous, so I make a generator, and the list from it, and sum it.

In [0]:
def gen_even_fib_under(x, i = 1, j = 1):
  
  while j < x:
    if j % 2 == 0:
      yield j
    i, j = j, i +j

In [14]:
%timeit sum([i for i in gen_even_fib_under(4000000)])

100000 loops, best of 3: 6.38 µs per loop

## Direct sum it in the function

In [0]:
def sum_even_fib_under(x):
  
  i = j = 1
  f = 0
  
  while j < x:    
    if j % 2 == 0:
      f += j
    i, j = j, i +j
    
  return f

In [16]:
%timeit sum_even_fib_under(4000000)

100000 loops, best of 3: 5.91 µs per loop

# Largest prime factor
## Problem 3 
The prime factors of 13195 are 5, 7, 13 and 29.

What is the largest prime factor of the number 600851475143 ?

### Define a prime number generator

In [0]:
def prime_gen(x):


  for i in range(2, x):
    if i == 2:
      yield 2
    else:
      e = int(i**.5) +1
      for j in range(2, e+1):
        if i % j == 0:
          break
        elif j < e:
          continue
        else:
          yield i

Test it

In [18]:
for i in prime_gen(20):
  print(i)

2
3
5
7
11
13
17
19

Count through the prime number list, divide the number to be tested by the prime number generated, to see if it is a factor.

In [0]:
def largest_prime_factor(x, i = 2):
  
  g = prime_gen(int(x**(1/2)))
  j = next(g)
  
  while x >= j**2:
    while x % j == 0:
      x //= j
      i = j
    j = next(g)
      
  return max(x, i)

test it

In [20]:
%time largest_prime_factor(21*79*97*199)

CPU times: user 211 µs, sys: 0 ns, total: 211 µs
Wall time: 219 µs

199

it works, let's try the number in the question

In [21]:
%time largest_prime_factor(600851475143)

CPU times: user 1.91 ms, sys: 1.02 ms, total: 2.93 ms
Wall time: 3.3 ms

6857

it works, but it is actually slow if the number is very large.

In [22]:
%time largest_prime_factor(30963359665568101)

CPU times: user 6.09 s, sys: 1.03 ms, total: 6.09 s
Wall time: 6.1 s

559784493077

Let's define a function without the prime generator.

In [0]:
def factor(x, f=2):
    
    factor = 1
    
    while x >= f*f:
        while x % f == 0:
            x = int(x/f)
            factor = f
            print(factor,'\t\t', x)    # for debug purpose only
        f += 1
        
    print(f'x = {x},\nlast factor = {factor}')
    return max(x, factor)

the right one after I fixed the bug

In [0]:
def factor2(x, f=2):
    
    factor = 1
    
    while x >= f*f:
        while x % f == 0:
            x = int(x//f)
            factor = f
            print(factor,'\t\t', x)  # for debug purpose only
        f += 1
        
    print(f'x = {x},\nlast factor = {factor}')
    return max(x, factor)

In [25]:
factor(19*19*19*19*19*19*19*19*19*1999989899)

19 		 33966954531029721088
32 		 1061467329094678784
32 		 33170854034208712
x = 33170854034208712,
last factor = 32

33170854034208712

In [26]:
factor2(19*19*19*19*19*19*19*19*19*1999989899)

19 		 33966954531029722859
19 		 1787734449001564361
19 		 94091286789556019
19 		 4952172988924001
19 		 260640683627579
19 		 13717930717241
19 		 721996353539
19 		 37999808081
19 		 1999989899
43 		 46511393
149 		 312157
541 		 577
x = 577,
last factor = 541

577

In [27]:
%time factor(307963037558124965010)

2 		 153981518779062484992
2 		 76990759389531242496
2 		 38495379694765621248
2 		 19247689847382810624
2 		 9623844923691405312
2 		 4811922461845702656
2 		 2405961230922851328
2 		 1202980615461425664
2 		 601490307730712832
2 		 300745153865356416
2 		 150372576932678208
2 		 75186288466339104
2 		 37593144233169552
2 		 18796572116584776
2 		 9398286058292388
2 		 4699143029146194
2 		 2349571514573097
3 		 783190504857699
3 		 261063501619233
3 		 87021167206411
x = 87021167206411,
last factor = 3
CPU times: user 2.01 s, sys: 3.02 ms, total: 2.02 s
Wall time: 2.02 s

87021167206411

In [28]:
%time factor2(307963037558124965010)

2 		 153981518779062482505
3 		 51327172926354160835
5 		 10265434585270832167
29 		 353980502940373523
82467481 		 4292364683
x = 4292364683,
last factor = 82467481
CPU times: user 17.3 s, sys: 4.13 ms, total: 17.3 s
Wall time: 17.3 s

4292364683

This is much faster than the one utilized a generator. To me this means generator in this case is a very expensive fuction.

In [29]:
%time factor2(30796303755812496501)

3 		 10265434585270832167
29 		 353980502940373523
82467481 		 4292364683
x = 4292364683,
last factor = 82467481
CPU times: user 17.3 s, sys: 6.01 ms, total: 17.3 s
Wall time: 17.3 s

4292364683

## function failure
if the tested number is large enough the test will fail, my **factor()** function, and will return a wrong number, I believe this is related to the kernal limit, I don't know if it is possible to fix it. I don't even know when the function will fail

### I think I figured it out:



> the integer division will yield a float number, the pricission of the float make the big integer division unreliable, the example below showed:
the division got a whole number, but the mode give a small remainder. The remainder is so small that it is rounded to zero automatically (omitted, not necessary any more).


### I did figure it now:

> integer division is not reliable, but floor division is:

>645372136089564734321/19      =     3396695453102972**1088**








>645372136089564734321//19     =     3396695453102972**2859**

# Largest palindrome product
## Problem 4 
A palindromic number reads the same both ways. The largest palindrome made from the product of two 2-digit numbers is 9009 = 91 × 99.

Find the largest palindrome made from the product of two 3-digit numbers.

In [0]:
def palindrome(s=1000, e=9999):
  
  
  result = 0
  for i in range(s, e+1):
    for j in range(s, e+1):
      ij = i*j
      product_i_j = str(ij)
      if product_i_j == product_i_j[-1::-1]:
        if ij  > result:
          result = ij
          ii, jj = i, j
  print(f'{result} = {ii} X {jj}')
  return result

In [31]:
%timeit palindrome(100, 1000)

906609 = 913 X 993
906609 = 913 X 993
906609 = 913 X 993
906609 = 913 X 993
1 loop, best of 3: 302 ms per loop

# Smallest multiple
## Problem 5 
2520 is the smallest number that can be divided by each of the numbers from 1 to 10 without any remainder.

What is the smallest positive number that is evenly divisible by all of the numbers from 1 to 20?

### Define a function to find all the prime factor of a number

In [0]:
def factor_finder(n, j=2):
  
  
  factor_list=[]
  
  if n == 2:
    return [2]
  elif n == 3:
    return [3]
  else:
    while n >= j*2:
      while n % j == 0:
        n = int(n//j)
        factor_list.append(j)
      j += 1
      
  if n > 1:
    factor_list.append(n)
  
  return factor_list

## Make a long list from all prime factor's from all the numbers to test
then find the longest repition sequence for each prime factor in the list, that is what we are going to keep.Then multiply them together.
ucomment the print will give you a idea how this works.

In [0]:
def smallest_multiples(n):
  
  
  from functools import reduce
   
  factor_list = []
  final_list = []
  
  for i in range(2, n+1):
    factor_list += (factor_finder(i))
  #print(factor_list)
  
  
  for i in set(factor_list):
    l1 = []
    l2 =[]
    for j in factor_list:
      if j == i:
        l1.append(j)
      else:
        if len(l1) > len(l2):
          l2 = l1
          l1= []
        else:
          l1 = []
    #print(l2)
    final_list += l2
  #print(final_list)
  
  return np.array(final_list).cumprod()[-1], reduce((lambda x, y: x*y), final_list)

In [34]:
%time 

smallest_multiples(400)

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 10.7 µs

(2596091279634863360,
 59667938474323557926610970384107539796305717355014061670120366929881205532187367293878763402540062687069192396177530529433679744512785143511161505144900493481243179036448000)

Sadly, the numpy function failed to get me the answer


> dtype="object" fixes it. [Stack Overflow](https://stackoverflow.com/questions/53755046/numpy-large-integer-failed)

In [35]:
%%time
def gcd(x,y): return y and gcd(y, x % y) or x
def lcm(x,y): return x * y / gcd(x,y)

n = 1
for i in range(1, 201):
     n = lcm(n, i)
print(n)

2.4327992077418156e+274
CPU times: user 1.03 ms, sys: 0 ns, total: 1.03 ms
Wall time: 1.23 ms

This is a great code I fond on the internet, but I can not understand