<a href="https://colab.research.google.com/github/uremember809/Project-Euler/blob/master/Project_Euler_(61_65).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%load_ext lab_black
import itertools

The lab_black extension is already loaded. To reload it, use:
  %reload_ext lab_black


<h2>Cyclical figurate numbers</h2><div id="problem_info"><h3>Problem 61 </h3></div>
<div class="problem_content" role="problem">
<p>Triangle, square, pentagonal, hexagonal, heptagonal, and octagonal numbers are all figurate (polygonal) numbers and are generated by the following formulae:</p>
<table><tbody><tr><td>Triangle</td>
<td>&nbsp;</td>
<td>P<sub>3,<i>n</i></sub>=<i>n</i>(<i>n</i>+1)/2</td>
<td>&nbsp;</td>
<td>1, 3, 6, 10, 15, ...</td>
</tr><tr><td>Square</td>
<td>&nbsp;</td>
<td>P<sub>4,<i>n</i></sub>=<i>n</i><sup>2</sup></td>
<td>&nbsp;</td>
<td>1, 4, 9, 16, 25, ...</td>
</tr><tr><td>Pentagonal</td>
<td>&nbsp;</td>
<td>P<sub>5,<i>n</i></sub>=<i>n</i>(3<i>n</i>-1)/2</td>
<td>&nbsp;</td>
<td>1, 5, 12, 22, 35, ...</td>
</tr><tr><td>Hexagonal</td>
<td>&nbsp;</td>
<td>P<sub>6,<i>n</i></sub>=<i>n</i>(2<i>n</i>-1)</td>
<td>&nbsp;</td>
<td>1, 6, 15, 28, 45, ...</td>
</tr><tr><td>Heptagonal</td>
<td>&nbsp;</td>
<td>P<sub>7,<i>n</i></sub>=<i>n</i>(5<i>n</i>-3)/2</td>
<td>&nbsp;</td>
<td>1, 7, 18, 34, 55, ...</td>
</tr><tr><td>Octagonal</td>
<td>&nbsp;</td>
<td>P<sub>8,<i>n</i></sub>=<i>n</i>(3<i>n</i>-2)</td>
<td>&nbsp;</td>
<td>1, 8, 21, 40, 65, ...</td>
</tr></tbody></table><p>The ordered set of three 4-digit numbers: 8128, 2882, 8281, has three interesting properties.</p>
<ol><li>The set is cyclic, in that the last two digits of each number is the first two digits of the next number (including the last number with the first).</li>
<li>Each polygonal type: triangle (P<sub>3,127</sub>=8128), square (P<sub>4,91</sub>=8281), and pentagonal (P<sub>5,44</sub>=2882), is represented by a different number in the set.</li>
<li>This is the only set of 4-digit numbers with this property.</li>
</ol><p>Find the sum of the only ordered set of six cyclic 4-digit numbers for which each polygonal type: triangle, square, pentagonal, hexagonal, heptagonal, and octagonal, is represented by a different number in the set.</p>

</div>

In [0]:
    %%time
    import itertools

    def tri(n):
        return n * (n + 1) // 2

    tri_={}
    for n in itertools.count():
        a=tri(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=="0" or str(a)[-2]=='0': continue
        tri_[n]=('tri', n,a)


    def tri_r(n):
        return int((-1 + (1 + 8 * n) ** .5) // 2)


    def sq(n):
        return n ** 2 // 1
    def sq_r(n):
        return int(n ** .5 // 1)
    sq_={}
    for n in itertools.count():
        a=sq(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        sq_[n]=('sq',n, a)



    def pent(n):
        return n * (3 * n - 1) // 2
    def pent_r(n):
        return int((1 + (1 + 24 * n) ** .5) // 6)
    pent_={}
    for n in itertools.count():
        a=pent(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        pent_[n] =('pent',n, a)



    def hexa(n):
        return n * (2 * n - 1) // 1
    def hexa_r(n):
        return int((1 + (1 + 8 * n) ** .5) // 4)
    hexa_={}
    for n in itertools.count():
        a=hexa(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        hexa_[n] =('hexa',n, a)



    def hep(n):
        return n * (5 * n - 3) // 2
    def hep_r(n):
        return int((3 + (9 + 40 * n) ** .5) // 10)
    hep_={}
    for n in itertools.count():
        a=hep(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        hep_[n]=('hep',n, a)



    def octa(n):
        return n * (3 * n - 2) // 1
    def octa_r(n):
        return int((2 + (4 + 12 * n) ** .5) // 6)
    octa_={}
    for n in itertools.count():
        a=octa(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        octa_[n]=('octa',n, a)


    full_list = []
    for i in [tri_, sq_, pent_, hexa_, hep_, octa_]:
        for j in i:
            full_list.append(i[j])

    for i in full_list:
        if i[0]=='tri':
            
            for j in full_list:
                if j[0] == i[0] or i[1] == j[1]:
                    continue
                tail = i[2] % 100
                head = j[2] // 100
                if head == tail:
                    for k in full_list:
                        if (
                            len(set((i[0], j[0], k[0]))) == 3
                            and len(set((i[1], j[1], k[1]))) == 3
                        ):
                            tail = j[2] % 100
                            head = k[2] // 100
                            if head == tail:
                                for l in full_list:
                                    if (
                                        len(set((i[0], j[0], k[0], l[0]))) == 4
                                        and len(set((i[1], j[1], k[1], l[1]))) == 4
                                    ):
                                        tail = k[2] % 100
                                        head = l[2] // 100
                                        if head == tail:
                                            for m in full_list:
                                                if (
                                                    len(
                                                        set(
                                                            (
                                                             i[0], j[0], k[0], l[0], m[0],
                                                            )
                                                        )
                                                    )
                                                    == 5
                                                    and len(
                                                        set(
                                                            (
                                                             i[1], j[1], k[1], l[1], m[1],
                                                            )
                                                        )
                                                    )
                                                    == 5
                                                ):
                                                    tail = l[2] % 100
                                                    head = m[2] // 100
                                                    if head == tail:
                                                        for n in full_list:
                                                            if (
                                                                len(
                                                                    set(
                                                                        (
                                                                         i[0], j[0], k[0], l[0], m[0], n[0],
                                                                        )
                                                                    )
                                                                )
                                                                == 6
                                                                and len(
                                                                    set(
                                                                        (
                                                                         i[1], j[1], k[1], l[1], m[1], n[1],
                                                                        )
                                                                    )
                                                                )
                                                                == 6
                                                            ):
                                                                tail = m[2] % 100
                                                                head = n[2] // 100
                                                                if (
                                                                    head == tail
                                                                    and n[2] % 100
                                                                    == i[2] // 100
                                                                ):
                                                                    print(
                                                                        i, j, k, l, m, n
                                                                    )

('tri', 128, 8256) ('sq', 75, 5625) ('hep', 32, 2512) ('octa', 21, 1281) ('hexa', 64, 8128) ('pent', 44, 2882)
CPU times: user 315 ms, sys: 0 ns, total: 315 ms
Wall time: 314 ms

In [0]:
    %%time
    import itertools

    def tri(n):
        return n * (n + 1) // 2

    tri_={}
    for n in itertools.count():
        a=tri(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=="0" or str(a)[-2]=='0': continue
        tri_[n]=('tri', n,a)


    def tri_r(n):
        return int((-1 + (1 + 8 * n) ** .5) // 2)


    def sq(n):
        return n ** 2 // 1
    def sq_r(n):
        return int(n ** .5 // 1)
    sq_={}
    for n in itertools.count():
        a=sq(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        sq_[n]=('sq',n, a)



    def pent(n):
        return n * (3 * n - 1) // 2
    def pent_r(n):
        return int((1 + (1 + 24 * n) ** .5) // 6)
    pent_={}
    for n in itertools.count():
        a=pent(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        pent_[n] =('pent',n, a)



    def hexa(n):
        return n * (2 * n - 1) // 1
    def hexa_r(n):
        return int((1 + (1 + 8 * n) ** .5) // 4)
    hexa_={}
    for n in itertools.count():
        a=hexa(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        hexa_[n] =('hexa',n, a)



    def hep(n):
        return n * (5 * n - 3) // 2
    def hep_r(n):
        return int((3 + (9 + 40 * n) ** .5) // 10)
    hep_={}
    for n in itertools.count():
        a=hep(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        hep_[n]=('hep',n, a)



    def octa(n):
        return n * (3 * n - 2) // 1
    def octa_r(n):
        return int((2 + (4 + 12 * n) ** .5) // 6)
    octa_={}
    for n in itertools.count():
        a=octa(n)
        if a<=1000: continue
        if a >= 10000: break
        if str(a)[-1]=='0' or str(a)[-2]=='0': continue
        octa_[n]=('octa',n, a)


    full_list = []
    for i in [tri_, sq_, pent_, hexa_, hep_, octa_]:
        for j in i:
            full_list.append(i[j])

    for i in full_list:
        if i[0]=='hep':
            
            for j in full_list:
                if j[0] == i[0] or i[1] == j[1]:
                    continue
                tail = i[2] % 100
                head = j[2] // 100
                if head == tail:
                    for k in full_list:
                        if (
                            k[0] not in set((i[0], j[0])) and
                            k[1] not in set((i[1], j[1]))
                        ):
                            tail = j[2] % 100
                            head = k[2] // 100
                            if head == tail:
                                for l in full_list:
                                    if (
                                        l[0] not in (set((i[0], j[0], k[0]))) and 
                                        l[1] not in set((i[1], j[1], k[1]))
                                    ):
                                        tail = k[2] % 100
                                        head = l[2] // 100
                                        if head == tail:
                                            for m in full_list:
                                                if ((m[0] not in set((i[0], j[0], k[0], l[0])))
                                                    and m[1] not in (set((i[1], j[1], k[1], l[1])))
                                                ):
                                                    tail = l[2] % 100
                                                    head = m[2] // 100
                                                    if head == tail:
                                                        for n in full_list:
                                                            if (
                                                                n[0] not in(set((i[0], j[0], k[0], l[0], m[0]))) and
                                                                n[1] not in (set((i[1], j[1], k[1], l[1], m[1])))
                                                            ):
                                                                tail = m[2] % 100
                                                                head = n[2] // 100
                                                                if (
                                                                    head == tail
                                                                    and n[2] % 100== i[2] // 100
                                                                ):
                                                                    print(i, j, k, l, m, n)

('hep', 32, 2512) ('octa', 21, 1281) ('hexa', 64, 8128) ('pent', 44, 2882) ('tri', 128, 8256) ('sq', 75, 5625)
CPU times: user 154 ms, sys: 6.72 ms, total: 161 ms
Wall time: 159 ms

In [0]:
for i in (tri_, sq_, pent_, hexa_, hep_, octa_):
    print(len(i))

69
53
37
34
36
24

<h2>Cubic permutations</h2><div id="problem_info"><h3>Problem 62 </h3></div>
<div class="problem_content" role="problem">
<p>The cube, 41063625 (345<sup>3</sup>), can be permuted to produce two other cubes: 56623104 (384<sup>3</sup>) and 66430125 (405<sup>3</sup>). In fact, 41063625 is the smallest cube which has exactly three permutations of its digits which are also cube.</p>
<p>Find the smallest cube for which exactly five permutations of its digits are cube.</p>
</div>

In [0]:
%%time

cube_list = [sorted(list(str(n ** 3))) + [str(n ** 3)] for n in range(10000)]

(cube_list).sort()

for k, g in itertools.groupby(cube_list, lambda x: x[:-1]):
    k_group = list(g)
    len_group = len(k_group)
    if len_group == 5:
        # print(k, [num[-1] for num in k_group], len_group)
        five_min = min([int(num[-1]) for num in k_group])
        try:
            if five_min < min_:
                min_ = five_min
        except:
            min_ = five_min
print(min_)

127035954683
CPU times: user 80.4 ms, sys: 7.74 ms, total: 88.1 ms
Wall time: 86.7 ms

<h2>Powerful digit counts</h2><div id="problem_info"><h3>Problem 63 </h3></div>
<div class="problem_content" role="problem">

<p>The 5-digit number, 16807=7<sup>5</sup>, is also a fifth power. Similarly, the 9-digit number, 134217728=8<sup>9</sup>, is a ninth power.</p>
<p>How many <i>n</i>-digit positive integers exist which are also an <i>n</i>th power?</p>

</div>

In [0]:
%%time
def d(n):
    return len(str(n))


n = 0
for i in range(1, 10):
    for j in range(1, 100):
        if d(i ** j) == j:
            n += 1
        if i == 9 and d(i ** j) < j:
            break

            # print(i, j, i ** j)
print(n)

49
CPU times: user 3.46 ms, sys: 0 ns, total: 3.46 ms
Wall time: 2.74 ms

<h2>Odd period square roots</h2><div id="problem_info"><h3>Problem 64 </h3></div>
<div class="problem_content" role="problem">
<p>All square roots are periodic when written as continued fractions and can be written in the form:</p>
<div style="margin-left:20px;">
<table>$\sqrt N = a_0 + \frac{1}{a_1 + \frac{1}{a_2 + \frac{1}{a_3+...} }}$
<p>For example, let us consider $\sqrt{23}$:</p>
<div style="margin-left:20px;">
$\sqrt{23} = 4 + \sqrt{23} - 4 = 4 + \frac{1}{\frac{1}{\sqrt{23}-4}}=4+\frac{1}{1+\frac{\sqrt{23}-3}{7}}$</div>

<p>If we continue we would get the following expansion:</p>
<div style="margin-left:20px;">
$\sqrt{23} = 4+\frac{1}{{1+\frac{1}{3+\frac{1}{1+\frac{1}{8+...}}}}}$</div>
<p>The process can be summarised as follows:</p>
<table><tbody>
<tr>
<td><var>a</var><sub>0</sub> = 4,     </td>
<td>&nbsp;</td>
<td>$\frac{1}{\sqrt{23}-4}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{\sqrt{23}+4}{7}$</td>
<td>&nbsp;=&nbsp;1 +&nbsp;</td>
<td>$\frac{\sqrt{23}-3}{7}$</td>
</tr>
<tr>
<td><var>a</var><sub>1</sub> = 1,</td>
<td>&nbsp;</td>
<td>$\frac{7}{\sqrt{23}-3}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{7(\sqrt{23}+3)}{14}$ </td>
<td>&nbsp;=&nbsp;3 +&nbsp;</td>
<td>$\frac{\sqrt{23}-3}{2}$</td>
</tr>
<tr>
<td><var>a</var><sub>2</sub> = 3,</td>
<td>&nbsp;</td>
<td>$\frac{2}{\sqrt{23}-3}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{2(\sqrt{23}+3)}{14}$</td>
<td>&nbsp;=&nbsp;1 +&nbsp;</td>
<td>$\frac{\sqrt{23}-4}{7}$</td>
</tr>
<tr>
<td><var>a</var><sub>3</sub> = 1,</td>
<td>&nbsp;</td>
<td>$\frac{7}{\sqrt{23}-4}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{7(\sqrt{23}+4)}{7}$</td>
<td>&nbsp;=&nbsp;8 +&nbsp;</td>
<td>$\sqrt{23}-4$</td>
</tr>
<tr>
<td><var>a</var><sub>4</sub> = 8,</td>
<td>&nbsp;</td>
<td>$\frac{1}{\sqrt{23}-4}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{\sqrt{23}+4}{7}$</td>
<td>&nbsp;=&nbsp;1 +&nbsp;</td>
<td>$\frac{\sqrt{23}-3}{7}$</td>
</tr>
<tr>
<td><var>a</var><sub>5</sub> = 1,</td>
<td>&nbsp;</td>
<td>$\frac{7}{\sqrt{23}-3}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{7(\sqrt{23}+3)}{14}$</td>
<td>&nbsp;=&nbsp;3 +&nbsp;</td>
<td>$\frac{\sqrt{23}-3}{2}$</td>
</tr>
<tr>
<td><var>a</var><sub>6</sub> = 3,</td>
<td>&nbsp;</td>
<td>$\frac{2}{\sqrt{23}-3}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{2(\sqrt{23}+3)}{14}$</td>
<td>&nbsp;=&nbsp;1 +&nbsp;</td>
<td>$\frac{\sqrt{23}-4}{7}$</td>
</tr>
<tr>
<td><var>a</var><sub>7</sub> = 1,</td>
<td>&nbsp;</td>
<td>$\frac{7}{\sqrt{23}-4}$</td>
<td>&nbsp;=&nbsp;</td>
<td>$\frac{7(\sqrt{23}+4)}{7}$</td>
<td>&nbsp;=&nbsp;8 +&nbsp;</td>
<td>$\sqrt{23}-4$</td>
</tr>
</tbody></table>
<p>It can be seen that the sequence is repeating. For conciseness, we use the notation $\sqrt{23}$ = [4;(1,3,1,8)], to indicate that the block (1,3,1,8) repeats indefinitely.</p>

<p>The first ten continued fraction representations of (irrational) square roots are:</p>
<p style="margin-left:20px;">$\sqrt2=[1;(2)]$, period=1<br>
$\sqrt3=[1;(1,2)]$, period=2<br>
$\sqrt5=[2;(4)]$, period=1<br>
$\sqrt6=[2;(2,4)]$, period=2<br>
$\sqrt7=[2;(1,1,1,4)]$, period=4<br>
$\sqrt8=[2;(1,4)]$, period=2<br>
$\sqrt10=[3;(6)]$, period=1<br>
$\sqrt11=[3;(3,6)]$, period=2<br>
$\sqrt12= [3;(2,6)]$, period=2<br>
$\sqrt13=[3;(1,1,1,1,6)]$, period=5</p>
<p>Exactly four continued fractions, for <var>$N \le 13$, have an odd period.</p>
<p>How many continued fractions for <var>$N \le 10000$ have an odd period?</p>
</div>

In [0]:
%%time
def root(n):
    m = 0
    d = 1
    r = n ** .5 // 1
    yield m, d, int(r)
    a = r

    while 1:

        m = d * a - m
        d = (n - m ** 2) / d
        a = ((r + m) / d) // 1
        yield int(m), int(d), int(a)


def cyc_root(n):
    a = {}
    for i, n in enumerate(root(n)):
        a[i] = n
        if i < 2:
            c = a[i]
            l = [c]
        elif n != c:
            l += [n]
        else:
            break

    # print(a[0], l, len(l))
    return len(l)


odd_count = 0
for x in range(2, 10001):
    if x ** .5 % 1 == 0:
        continue
    if cyc_root(x) % 2 == 1:
        odd_count += 1
print(odd_count)

1322
CPU times: user 543 ms, sys: 0 ns, total: 543 ms
Wall time: 545 ms

<h2>Convergents of e</h2><div id="problem_info"><h3>Problem 65 </h3></div>
<div class="problem_content" role="problem">
<p>The square root of 2 can be written as an infinite continued fraction.</p>
<div style="margin-left:20px;">
<table border="0" cellspacing="0" cellpadding="0"><tbody><tr><td>√2 = 1 +</td>
<td colspan="4" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
</tr><tr><td>&nbsp;</td>
<td>2 +</td>
<td colspan="3" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>2 +</td>
<td colspan="2" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>2 +</td>
<td style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>2 + ...</td>
</tr></tbody></table></div>
<p>The infinite continued fraction can be written, √2 = [1;(2)], (2) indicates that 2 repeats <i>ad infinitum</i>. In a similar way, √23 = [4;(1,3,1,8)].</p>
<p>It turns out that the sequence of partial values of continued fractions for square roots provide the best rational approximations. Let us consider the convergents for √2.</p>
<div style="margin-left:20px;">

<table border="0" cellspacing="0" cellpadding="0"><tbody><tr><td>1 +</td>
<td style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>= 3/2</td>
</tr><tr><td>&nbsp;</td>
<td><div style="text-align:center;">2</div></td>
<td>&nbsp;</td>
</tr></tbody></table><table border="0" cellspacing="0" cellpadding="0"><tbody><tr><td>1 +</td>
<td colspan="2" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>= 7/5</td>
</tr><tr><td>&nbsp;</td>
<td>2 +</td>
<td style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td><div style="text-align:center;">2</div></td>
<td>&nbsp;</td>
</tr></tbody></table><table border="0" cellspacing="0" cellpadding="0"><tbody><tr><td>1 +</td>
<td colspan="3" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>= 17/12</td>
</tr><tr><td>&nbsp;</td>
<td>2 +</td>
<td colspan="2" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>&nbsp;</td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>2 +</td>
<td style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>&nbsp;</td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td><div style="text-align:center;">2</div></td>
<td>&nbsp;</td>
</tr></tbody></table><table border="0" cellspacing="0" cellpadding="0"><tbody><tr><td>1 +</td>
<td colspan="4" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>= 41/29</td>
</tr><tr><td>&nbsp;</td>
<td>2 +</td>
<td colspan="3" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>2 +</td>
<td colspan="2" style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>&nbsp;</td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>2 +</td>
<td style="border-bottom:1px solid #000;"><div style="text-align:center;">1</div></td>
<td>&nbsp;</td>
</tr><tr><td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td>&nbsp;</td>
<td><div style="text-align:center;">2</div></td>
<td>&nbsp;</td>
</tr></tbody></table></div>
<p>Hence the sequence of the first ten convergents for √2 are:</p>
<div class="note">1, 3/2, 7/5, 17/12, 41/29, 99/70, 239/169, 577/408, 1393/985, 3363/2378, ...</div>
<p>What is most surprising is that the important mathematical constant,<br><i>e</i> = [2; 1,2,1, 1,4,1, 1,6,1 , ... , 1,2<i>k</i>,1, ...].</p>
<p>The first ten terms in the sequence of convergents for <i>e</i> are:</p>
<div class="note">2, 3, 8/3, 11/4, 19/7, 87/32, 106/39, 193/71, 1264/465, 1457/536, ...</div>
<p>The sum of digits in the numerator of the 10<sup>th</sup> convergent is 1+4+5+7=17.</p>
<p>Find the sum of digits in the numerator of the 100<sup>th</sup> convergent of the continued fraction for <i>e</i>.</p>
</div><br>
<br></div>

In [0]:
%%time
def serial():
    for i in itertools.count(1):
        for j in (1, 2 * i, 1):
            yield j


def e(n):
    if n == 0:
        return 2, 1, 2
    if n == 1:
        return 3, 1, 3
    l = []
    for i, s in enumerate(serial()):
        if i == n:
            break
        l += [s]

    i, j, k = l[-2], 1, l[-1]
    for x in l[-3::-1]:
        i, j, k = x, k, i * k + j
    return 2 * (k * i + j) + k, k * i + j, 2 + k / (k * i + j)


result = sum(list(int(i) for i in str(e(99)[0])))

print(f"the result is {result}")

the result is 272
CPU times: user 326 µs, sys: 12 µs, total: 338 µs
Wall time: 259 µs